/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

int hkinodyn(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int hkinodyn_alloc_mem(void);
int hkinodyn_init_mem(int mem);
void hkinodyn_free_mem(int mem);
int hkinodyn_checkout(void);
void hkinodyn_release(int mem);
void hkinodyn_incref(void);
void hkinodyn_decref(void);
casadi_int hkinodyn_n_out(void);
casadi_int hkinodyn_n_in(void);
casadi_real hkinodyn_default_in(casadi_int i);
const char* hkinodyn_name_in(casadi_int i);
const char* hkinodyn_name_out(casadi_int i);
const casadi_int* hkinodyn_sparsity_in(casadi_int i);
const casadi_int* hkinodyn_sparsity_out(casadi_int i);
int hkinodyn_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#ifdef __cplusplus
} /* extern "C" */
#endif
