/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package lcmtypes;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class opt_sol_lcmt implements lcm.lcm.LCMEncodable
{
    public int N;
    public int contacts[][];
    public float qdummy[][];
 
    public opt_sol_lcmt()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x193f4d961a6767b2L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(lcmtypes.opt_sol_lcmt.class))
            return 0L;
 
        classes.add(lcmtypes.opt_sol_lcmt.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeInt(this.N); 
 
        for (int a = 0; a < this.N; a++) {
            for (int b = 0; b < 4; b++) {
                outs.writeInt(this.contacts[a][b]); 
            }
        }
 
        for (int a = 0; a < this.N; a++) {
            for (int b = 0; b < 12; b++) {
                outs.writeFloat(this.qdummy[a][b]); 
            }
        }
 
    }
 
    public opt_sol_lcmt(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public opt_sol_lcmt(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static lcmtypes.opt_sol_lcmt _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        lcmtypes.opt_sol_lcmt o = new lcmtypes.opt_sol_lcmt();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.N = ins.readInt();
 
        this.contacts = new int[(int) N][(int) 4];
        for (int a = 0; a < this.N; a++) {
            for (int b = 0; b < 4; b++) {
                this.contacts[a][b] = ins.readInt();
            }
        }
 
        this.qdummy = new float[(int) N][(int) 12];
        for (int a = 0; a < this.N; a++) {
            for (int b = 0; b < 12; b++) {
                this.qdummy[a][b] = ins.readFloat();
            }
        }
 
    }
 
    public lcmtypes.opt_sol_lcmt copy()
    {
        lcmtypes.opt_sol_lcmt outobj = new lcmtypes.opt_sol_lcmt();
        outobj.N = this.N;
 
        outobj.contacts = new int[(int) N][(int) 4];
        for (int a = 0; a < this.N; a++) {
            System.arraycopy(this.contacts[a], 0, outobj.contacts[a], 0, 4);        }
 
        outobj.qdummy = new float[(int) N][(int) 12];
        for (int a = 0; a < this.N; a++) {
            System.arraycopy(this.qdummy[a], 0, outobj.qdummy[a], 0, 12);        }
 
        return outobj;
    }
 
}

