"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class MHPC_Data_lcmt(object):
    __slots__ = ["reset_mpc", "MS", "mpctime", "pos", "eul", "qJ", "vWorld", "eulrate", "qJd"]

    __typenames__ = ["boolean", "boolean", "double", "float", "float", "float", "float", "float", "float"]

    __dimensions__ = [None, None, None, [3], [3], [12], [3], [3], [12]]

    def __init__(self):
        self.reset_mpc = False
        self.MS = False
        self.mpctime = 0.0
        self.pos = [ 0.0 for dim0 in range(3) ]
        self.eul = [ 0.0 for dim0 in range(3) ]
        self.qJ = [ 0.0 for dim0 in range(12) ]
        self.vWorld = [ 0.0 for dim0 in range(3) ]
        self.eulrate = [ 0.0 for dim0 in range(3) ]
        self.qJd = [ 0.0 for dim0 in range(12) ]

    def encode(self):
        buf = BytesIO()
        buf.write(MHPC_Data_lcmt._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">bbd", self.reset_mpc, self.MS, self.mpctime))
        buf.write(struct.pack('>3f', *self.pos[:3]))
        buf.write(struct.pack('>3f', *self.eul[:3]))
        buf.write(struct.pack('>12f', *self.qJ[:12]))
        buf.write(struct.pack('>3f', *self.vWorld[:3]))
        buf.write(struct.pack('>3f', *self.eulrate[:3]))
        buf.write(struct.pack('>12f', *self.qJd[:12]))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != MHPC_Data_lcmt._get_packed_fingerprint():
            raise ValueError("Decode error")
        return MHPC_Data_lcmt._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = MHPC_Data_lcmt()
        self.reset_mpc = bool(struct.unpack('b', buf.read(1))[0])
        self.MS = bool(struct.unpack('b', buf.read(1))[0])
        self.mpctime = struct.unpack(">d", buf.read(8))[0]
        self.pos = struct.unpack('>3f', buf.read(12))
        self.eul = struct.unpack('>3f', buf.read(12))
        self.qJ = struct.unpack('>12f', buf.read(48))
        self.vWorld = struct.unpack('>3f', buf.read(12))
        self.eulrate = struct.unpack('>3f', buf.read(12))
        self.qJd = struct.unpack('>12f', buf.read(48))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if MHPC_Data_lcmt in parents: return 0
        tmphash = (0xfcc6a78db3f0ef2b) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if MHPC_Data_lcmt._packed_fingerprint is None:
            MHPC_Data_lcmt._packed_fingerprint = struct.pack(">Q", MHPC_Data_lcmt._get_hash_recursive([]))
        return MHPC_Data_lcmt._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

