"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class MHPC_Command_lcmt(object):
    __slots__ = ["N_mpcsteps", "mpc_times", "torque", "eul", "pos", "qJ", "vWorld", "eulrate", "qJd", "contacts", "statusTimes", "solve_time"]

    __typenames__ = ["int32_t", "float", "float", "float", "float", "float", "float", "float", "float", "int32_t", "float", "float"]

    __dimensions__ = [None, [3], [3, 12], [3, 3], [3, 3], [3, 12], [3, 3], [3, 3], [3, 12], [3, 4], [3, 4], None]

    def __init__(self):
        self.N_mpcsteps = 0
        self.mpc_times = [ 0.0 for dim0 in range(3) ]
        self.torque = [ [ 0.0 for dim1 in range(12) ] for dim0 in range(3) ]
        self.eul = [ [ 0.0 for dim1 in range(3) ] for dim0 in range(3) ]
        self.pos = [ [ 0.0 for dim1 in range(3) ] for dim0 in range(3) ]
        self.qJ = [ [ 0.0 for dim1 in range(12) ] for dim0 in range(3) ]
        self.vWorld = [ [ 0.0 for dim1 in range(3) ] for dim0 in range(3) ]
        self.eulrate = [ [ 0.0 for dim1 in range(3) ] for dim0 in range(3) ]
        self.qJd = [ [ 0.0 for dim1 in range(12) ] for dim0 in range(3) ]
        self.contacts = [ [ 0 for dim1 in range(4) ] for dim0 in range(3) ]
        self.statusTimes = [ [ 0.0 for dim1 in range(4) ] for dim0 in range(3) ]
        self.solve_time = 0.0

    def encode(self):
        buf = BytesIO()
        buf.write(MHPC_Command_lcmt._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">i", self.N_mpcsteps))
        buf.write(struct.pack('>3f', *self.mpc_times[:3]))
        for i0 in range(3):
            buf.write(struct.pack('>12f', *self.torque[i0][:12]))
        for i0 in range(3):
            buf.write(struct.pack('>3f', *self.eul[i0][:3]))
        for i0 in range(3):
            buf.write(struct.pack('>3f', *self.pos[i0][:3]))
        for i0 in range(3):
            buf.write(struct.pack('>12f', *self.qJ[i0][:12]))
        for i0 in range(3):
            buf.write(struct.pack('>3f', *self.vWorld[i0][:3]))
        for i0 in range(3):
            buf.write(struct.pack('>3f', *self.eulrate[i0][:3]))
        for i0 in range(3):
            buf.write(struct.pack('>12f', *self.qJd[i0][:12]))
        for i0 in range(3):
            buf.write(struct.pack('>4i', *self.contacts[i0][:4]))
        for i0 in range(3):
            buf.write(struct.pack('>4f', *self.statusTimes[i0][:4]))
        buf.write(struct.pack(">f", self.solve_time))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != MHPC_Command_lcmt._get_packed_fingerprint():
            raise ValueError("Decode error")
        return MHPC_Command_lcmt._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = MHPC_Command_lcmt()
        self.N_mpcsteps = struct.unpack(">i", buf.read(4))[0]
        self.mpc_times = struct.unpack('>3f', buf.read(12))
        self.torque = []
        for i0 in range(3):
            self.torque.append(struct.unpack('>12f', buf.read(48)))
        self.eul = []
        for i0 in range(3):
            self.eul.append(struct.unpack('>3f', buf.read(12)))
        self.pos = []
        for i0 in range(3):
            self.pos.append(struct.unpack('>3f', buf.read(12)))
        self.qJ = []
        for i0 in range(3):
            self.qJ.append(struct.unpack('>12f', buf.read(48)))
        self.vWorld = []
        for i0 in range(3):
            self.vWorld.append(struct.unpack('>3f', buf.read(12)))
        self.eulrate = []
        for i0 in range(3):
            self.eulrate.append(struct.unpack('>3f', buf.read(12)))
        self.qJd = []
        for i0 in range(3):
            self.qJd.append(struct.unpack('>12f', buf.read(48)))
        self.contacts = []
        for i0 in range(3):
            self.contacts.append(struct.unpack('>4i', buf.read(16)))
        self.statusTimes = []
        for i0 in range(3):
            self.statusTimes.append(struct.unpack('>4f', buf.read(16)))
        self.solve_time = struct.unpack(">f", buf.read(4))[0]
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if MHPC_Command_lcmt in parents: return 0
        tmphash = (0x5f55cf04f3c2c6de) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if MHPC_Command_lcmt._packed_fingerprint is None:
            MHPC_Command_lcmt._packed_fingerprint = struct.pack(">Q", MHPC_Command_lcmt._get_hash_recursive([]))
        return MHPC_Command_lcmt._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

