"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class visualize_quadState_lcmt(object):
    __slots__ = ["pos", "eul", "vWorld", "eulrate", "qJ", "qJd", "pFoot", "Jc", "qJdd", "torque"]

    __typenames__ = ["float", "float", "float", "float", "float", "float", "float", "float", "float", "float"]

    __dimensions__ = [[3], [3], [3], [3], [12], [12], [12], [12, 18], [12], [12]]

    def __init__(self):
        self.pos = [ 0.0 for dim0 in range(3) ]
        self.eul = [ 0.0 for dim0 in range(3) ]
        self.vWorld = [ 0.0 for dim0 in range(3) ]
        self.eulrate = [ 0.0 for dim0 in range(3) ]
        self.qJ = [ 0.0 for dim0 in range(12) ]
        self.qJd = [ 0.0 for dim0 in range(12) ]
        self.pFoot = [ 0.0 for dim0 in range(12) ]
        self.Jc = [ [ 0.0 for dim1 in range(18) ] for dim0 in range(12) ]
        self.qJdd = [ 0.0 for dim0 in range(12) ]
        self.torque = [ 0.0 for dim0 in range(12) ]

    def encode(self):
        buf = BytesIO()
        buf.write(visualize_quadState_lcmt._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack('>3f', *self.pos[:3]))
        buf.write(struct.pack('>3f', *self.eul[:3]))
        buf.write(struct.pack('>3f', *self.vWorld[:3]))
        buf.write(struct.pack('>3f', *self.eulrate[:3]))
        buf.write(struct.pack('>12f', *self.qJ[:12]))
        buf.write(struct.pack('>12f', *self.qJd[:12]))
        buf.write(struct.pack('>12f', *self.pFoot[:12]))
        for i0 in range(12):
            buf.write(struct.pack('>18f', *self.Jc[i0][:18]))
        buf.write(struct.pack('>12f', *self.qJdd[:12]))
        buf.write(struct.pack('>12f', *self.torque[:12]))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != visualize_quadState_lcmt._get_packed_fingerprint():
            raise ValueError("Decode error")
        return visualize_quadState_lcmt._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = visualize_quadState_lcmt()
        self.pos = struct.unpack('>3f', buf.read(12))
        self.eul = struct.unpack('>3f', buf.read(12))
        self.vWorld = struct.unpack('>3f', buf.read(12))
        self.eulrate = struct.unpack('>3f', buf.read(12))
        self.qJ = struct.unpack('>12f', buf.read(48))
        self.qJd = struct.unpack('>12f', buf.read(48))
        self.pFoot = struct.unpack('>12f', buf.read(48))
        self.Jc = []
        for i0 in range(12):
            self.Jc.append(struct.unpack('>18f', buf.read(72)))
        self.qJdd = struct.unpack('>12f', buf.read(48))
        self.torque = struct.unpack('>12f', buf.read(48))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if visualize_quadState_lcmt in parents: return 0
        tmphash = (0x7a716bd3af01e4c3) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if visualize_quadState_lcmt._packed_fingerprint is None:
            visualize_quadState_lcmt._packed_fingerprint = struct.pack(">Q", visualize_quadState_lcmt._get_hash_recursive([]))
        return visualize_quadState_lcmt._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

