/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package lcmtypes;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class visualize_quadState_lcmt implements lcm.lcm.LCMEncodable
{
    public float pos[];
    public float eul[];
    public float vWorld[];
    public float eulrate[];
    public float qJ[];
    public float qJd[];
    public float pFoot[];
    public float Jc[][];
    public float qJdd[];
    public float torque[];
 
    public visualize_quadState_lcmt()
    {
        pos = new float[3];
        eul = new float[3];
        vWorld = new float[3];
        eulrate = new float[3];
        qJ = new float[12];
        qJd = new float[12];
        pFoot = new float[12];
        Jc = new float[12][18];
        qJdd = new float[12];
        torque = new float[12];
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x7a716bd3af01e4c3L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(lcmtypes.visualize_quadState_lcmt.class))
            return 0L;
 
        classes.add(lcmtypes.visualize_quadState_lcmt.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        for (int a = 0; a < 3; a++) {
            outs.writeFloat(this.pos[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeFloat(this.eul[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeFloat(this.vWorld[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeFloat(this.eulrate[a]); 
        }
 
        for (int a = 0; a < 12; a++) {
            outs.writeFloat(this.qJ[a]); 
        }
 
        for (int a = 0; a < 12; a++) {
            outs.writeFloat(this.qJd[a]); 
        }
 
        for (int a = 0; a < 12; a++) {
            outs.writeFloat(this.pFoot[a]); 
        }
 
        for (int a = 0; a < 12; a++) {
            for (int b = 0; b < 18; b++) {
                outs.writeFloat(this.Jc[a][b]); 
            }
        }
 
        for (int a = 0; a < 12; a++) {
            outs.writeFloat(this.qJdd[a]); 
        }
 
        for (int a = 0; a < 12; a++) {
            outs.writeFloat(this.torque[a]); 
        }
 
    }
 
    public visualize_quadState_lcmt(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public visualize_quadState_lcmt(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static lcmtypes.visualize_quadState_lcmt _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        lcmtypes.visualize_quadState_lcmt o = new lcmtypes.visualize_quadState_lcmt();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.pos = new float[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.pos[a] = ins.readFloat();
        }
 
        this.eul = new float[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.eul[a] = ins.readFloat();
        }
 
        this.vWorld = new float[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.vWorld[a] = ins.readFloat();
        }
 
        this.eulrate = new float[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.eulrate[a] = ins.readFloat();
        }
 
        this.qJ = new float[(int) 12];
        for (int a = 0; a < 12; a++) {
            this.qJ[a] = ins.readFloat();
        }
 
        this.qJd = new float[(int) 12];
        for (int a = 0; a < 12; a++) {
            this.qJd[a] = ins.readFloat();
        }
 
        this.pFoot = new float[(int) 12];
        for (int a = 0; a < 12; a++) {
            this.pFoot[a] = ins.readFloat();
        }
 
        this.Jc = new float[(int) 12][(int) 18];
        for (int a = 0; a < 12; a++) {
            for (int b = 0; b < 18; b++) {
                this.Jc[a][b] = ins.readFloat();
            }
        }
 
        this.qJdd = new float[(int) 12];
        for (int a = 0; a < 12; a++) {
            this.qJdd[a] = ins.readFloat();
        }
 
        this.torque = new float[(int) 12];
        for (int a = 0; a < 12; a++) {
            this.torque[a] = ins.readFloat();
        }
 
    }
 
    public lcmtypes.visualize_quadState_lcmt copy()
    {
        lcmtypes.visualize_quadState_lcmt outobj = new lcmtypes.visualize_quadState_lcmt();
        outobj.pos = new float[(int) 3];
        System.arraycopy(this.pos, 0, outobj.pos, 0, 3); 
        outobj.eul = new float[(int) 3];
        System.arraycopy(this.eul, 0, outobj.eul, 0, 3); 
        outobj.vWorld = new float[(int) 3];
        System.arraycopy(this.vWorld, 0, outobj.vWorld, 0, 3); 
        outobj.eulrate = new float[(int) 3];
        System.arraycopy(this.eulrate, 0, outobj.eulrate, 0, 3); 
        outobj.qJ = new float[(int) 12];
        System.arraycopy(this.qJ, 0, outobj.qJ, 0, 12); 
        outobj.qJd = new float[(int) 12];
        System.arraycopy(this.qJd, 0, outobj.qJd, 0, 12); 
        outobj.pFoot = new float[(int) 12];
        System.arraycopy(this.pFoot, 0, outobj.pFoot, 0, 12); 
        outobj.Jc = new float[(int) 12][(int) 18];
        for (int a = 0; a < 12; a++) {
            System.arraycopy(this.Jc[a], 0, outobj.Jc[a], 0, 18);        }
 
        outobj.qJdd = new float[(int) 12];
        System.arraycopy(this.qJdd, 0, outobj.qJdd, 0, 12); 
        outobj.torque = new float[(int) 12];
        System.arraycopy(this.torque, 0, outobj.torque, 0, 12); 
        return outobj;
    }
 
}

