/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by lcm-gen
 **/

#ifndef __visualize_quadTraj_lcmt_hpp__
#define __visualize_quadTraj_lcmt_hpp__

#include <lcm/lcm_coretypes.h>

#include <vector>


class visualize_quadTraj_lcmt
{
    public:
        int16_t    len;

        float      WB_plan_dur;

        float      SRB_plan_dur;

        float      WB_dt;

        float      SRB_dt;

        std::vector< std::vector< float > > pos;

        std::vector< std::vector< float > > eul;

        std::vector< std::vector< float > > vWorld;

        std::vector< std::vector< float > > eulrate;

        std::vector< std::vector< float > > qJ;

        std::vector< std::vector< float > > pFoot;

        std::vector< std::vector< float > > torque;

        std::vector< std::vector< float > > grf;

        std::vector< float > feas;

    public:
        /**
         * Encode a message into binary form.
         *
         * @param buf The output buffer.
         * @param offset Encoding starts at thie byte offset into @p buf.
         * @param maxlen Maximum number of bytes to write.  This should generally be
         *  equal to getEncodedSize().
         * @return The number of bytes encoded, or <0 on error.
         */
        inline int encode(void *buf, int offset, int maxlen) const;

        /**
         * Check how many bytes are required to encode this message.
         */
        inline int getEncodedSize() const;

        /**
         * Decode a message from binary form into this instance.
         *
         * @param buf The buffer containing the encoded message.
         * @param offset The byte offset into @p buf where the encoded message starts.
         * @param maxlen The maximum number of bytes to read while decoding.
         * @return The number of bytes decoded, or <0 if an error occured.
         */
        inline int decode(const void *buf, int offset, int maxlen);

        /**
         * Retrieve the 64-bit fingerprint identifying the structure of the message.
         * Note that the fingerprint is the same for all instances of the same
         * message type, and is a fingerprint on the message type definition, not on
         * the message contents.
         */
        inline static int64_t getHash();

        /**
         * Returns "visualize_quadTraj_lcmt"
         */
        inline static const char* getTypeName();

        // LCM support functions. Users should not call these
        inline int _encodeNoHash(void *buf, int offset, int maxlen) const;
        inline int _getEncodedSizeNoHash() const;
        inline int _decodeNoHash(const void *buf, int offset, int maxlen);
        inline static uint64_t _computeHash(const __lcm_hash_ptr *p);
};

int visualize_quadTraj_lcmt::encode(void *buf, int offset, int maxlen) const
{
    int pos = 0, tlen;
    int64_t hash = getHash();

    tlen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = this->_encodeNoHash(buf, offset + pos, maxlen - pos);
    if (tlen < 0) return tlen; else pos += tlen;

    return pos;
}

int visualize_quadTraj_lcmt::decode(const void *buf, int offset, int maxlen)
{
    int pos = 0, thislen;

    int64_t msg_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &msg_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (msg_hash != getHash()) return -1;

    thislen = this->_decodeNoHash(buf, offset + pos, maxlen - pos);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int visualize_quadTraj_lcmt::getEncodedSize() const
{
    return 8 + _getEncodedSizeNoHash();
}

int64_t visualize_quadTraj_lcmt::getHash()
{
    static int64_t hash = static_cast<int64_t>(_computeHash(NULL));
    return hash;
}

const char* visualize_quadTraj_lcmt::getTypeName()
{
    return "visualize_quadTraj_lcmt";
}

int visualize_quadTraj_lcmt::_encodeNoHash(void *buf, int offset, int maxlen) const
{
    int pos = 0, tlen;

    tlen = __int16_t_encode_array(buf, offset + pos, maxlen - pos, &this->len, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __float_encode_array(buf, offset + pos, maxlen - pos, &this->WB_plan_dur, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __float_encode_array(buf, offset + pos, maxlen - pos, &this->SRB_plan_dur, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __float_encode_array(buf, offset + pos, maxlen - pos, &this->WB_dt, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __float_encode_array(buf, offset + pos, maxlen - pos, &this->SRB_dt, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    for (int a0 = 0; a0 < this->len; a0++) {
        tlen = __float_encode_array(buf, offset + pos, maxlen - pos, &this->pos[a0][0], 3);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    for (int a0 = 0; a0 < this->len; a0++) {
        tlen = __float_encode_array(buf, offset + pos, maxlen - pos, &this->eul[a0][0], 3);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    for (int a0 = 0; a0 < this->len; a0++) {
        tlen = __float_encode_array(buf, offset + pos, maxlen - pos, &this->vWorld[a0][0], 3);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    for (int a0 = 0; a0 < this->len; a0++) {
        tlen = __float_encode_array(buf, offset + pos, maxlen - pos, &this->eulrate[a0][0], 3);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    for (int a0 = 0; a0 < this->len; a0++) {
        tlen = __float_encode_array(buf, offset + pos, maxlen - pos, &this->qJ[a0][0], 12);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    for (int a0 = 0; a0 < this->len; a0++) {
        tlen = __float_encode_array(buf, offset + pos, maxlen - pos, &this->pFoot[a0][0], 12);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    for (int a0 = 0; a0 < this->len; a0++) {
        tlen = __float_encode_array(buf, offset + pos, maxlen - pos, &this->torque[a0][0], 12);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    for (int a0 = 0; a0 < this->len; a0++) {
        tlen = __float_encode_array(buf, offset + pos, maxlen - pos, &this->grf[a0][0], 12);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    if(this->len > 0) {
        tlen = __float_encode_array(buf, offset + pos, maxlen - pos, &this->feas[0], this->len);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    return pos;
}

int visualize_quadTraj_lcmt::_decodeNoHash(const void *buf, int offset, int maxlen)
{
    int pos = 0, tlen;

    tlen = __int16_t_decode_array(buf, offset + pos, maxlen - pos, &this->len, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __float_decode_array(buf, offset + pos, maxlen - pos, &this->WB_plan_dur, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __float_decode_array(buf, offset + pos, maxlen - pos, &this->SRB_plan_dur, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __float_decode_array(buf, offset + pos, maxlen - pos, &this->WB_dt, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __float_decode_array(buf, offset + pos, maxlen - pos, &this->SRB_dt, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    try {
        this->pos.resize(this->len);
    } catch (...) {
        return -1;
    }
    for (int a0 = 0; a0 < this->len; a0++) {
        if(3) {
            this->pos[a0].resize(3);
            tlen = __float_decode_array(buf, offset + pos, maxlen - pos, &this->pos[a0][0], 3);
            if(tlen < 0) return tlen; else pos += tlen;
        }
    }

    try {
        this->eul.resize(this->len);
    } catch (...) {
        return -1;
    }
    for (int a0 = 0; a0 < this->len; a0++) {
        if(3) {
            this->eul[a0].resize(3);
            tlen = __float_decode_array(buf, offset + pos, maxlen - pos, &this->eul[a0][0], 3);
            if(tlen < 0) return tlen; else pos += tlen;
        }
    }

    try {
        this->vWorld.resize(this->len);
    } catch (...) {
        return -1;
    }
    for (int a0 = 0; a0 < this->len; a0++) {
        if(3) {
            this->vWorld[a0].resize(3);
            tlen = __float_decode_array(buf, offset + pos, maxlen - pos, &this->vWorld[a0][0], 3);
            if(tlen < 0) return tlen; else pos += tlen;
        }
    }

    try {
        this->eulrate.resize(this->len);
    } catch (...) {
        return -1;
    }
    for (int a0 = 0; a0 < this->len; a0++) {
        if(3) {
            this->eulrate[a0].resize(3);
            tlen = __float_decode_array(buf, offset + pos, maxlen - pos, &this->eulrate[a0][0], 3);
            if(tlen < 0) return tlen; else pos += tlen;
        }
    }

    try {
        this->qJ.resize(this->len);
    } catch (...) {
        return -1;
    }
    for (int a0 = 0; a0 < this->len; a0++) {
        if(12) {
            this->qJ[a0].resize(12);
            tlen = __float_decode_array(buf, offset + pos, maxlen - pos, &this->qJ[a0][0], 12);
            if(tlen < 0) return tlen; else pos += tlen;
        }
    }

    try {
        this->pFoot.resize(this->len);
    } catch (...) {
        return -1;
    }
    for (int a0 = 0; a0 < this->len; a0++) {
        if(12) {
            this->pFoot[a0].resize(12);
            tlen = __float_decode_array(buf, offset + pos, maxlen - pos, &this->pFoot[a0][0], 12);
            if(tlen < 0) return tlen; else pos += tlen;
        }
    }

    try {
        this->torque.resize(this->len);
    } catch (...) {
        return -1;
    }
    for (int a0 = 0; a0 < this->len; a0++) {
        if(12) {
            this->torque[a0].resize(12);
            tlen = __float_decode_array(buf, offset + pos, maxlen - pos, &this->torque[a0][0], 12);
            if(tlen < 0) return tlen; else pos += tlen;
        }
    }

    try {
        this->grf.resize(this->len);
    } catch (...) {
        return -1;
    }
    for (int a0 = 0; a0 < this->len; a0++) {
        if(12) {
            this->grf[a0].resize(12);
            tlen = __float_decode_array(buf, offset + pos, maxlen - pos, &this->grf[a0][0], 12);
            if(tlen < 0) return tlen; else pos += tlen;
        }
    }

    if(this->len) {
        this->feas.resize(this->len);
        tlen = __float_decode_array(buf, offset + pos, maxlen - pos, &this->feas[0], this->len);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    return pos;
}

int visualize_quadTraj_lcmt::_getEncodedSizeNoHash() const
{
    int enc_size = 0;
    enc_size += __int16_t_encoded_array_size(NULL, 1);
    enc_size += __float_encoded_array_size(NULL, 1);
    enc_size += __float_encoded_array_size(NULL, 1);
    enc_size += __float_encoded_array_size(NULL, 1);
    enc_size += __float_encoded_array_size(NULL, 1);
    enc_size += this->len * __float_encoded_array_size(NULL, 3);
    enc_size += this->len * __float_encoded_array_size(NULL, 3);
    enc_size += this->len * __float_encoded_array_size(NULL, 3);
    enc_size += this->len * __float_encoded_array_size(NULL, 3);
    enc_size += this->len * __float_encoded_array_size(NULL, 12);
    enc_size += this->len * __float_encoded_array_size(NULL, 12);
    enc_size += this->len * __float_encoded_array_size(NULL, 12);
    enc_size += this->len * __float_encoded_array_size(NULL, 12);
    enc_size += __float_encoded_array_size(NULL, this->len);
    return enc_size;
}

uint64_t visualize_quadTraj_lcmt::_computeHash(const __lcm_hash_ptr *)
{
    uint64_t hash = 0xcdf7562a37afd09aLL;
    return (hash<<1) + ((hash>>63)&1);
}

#endif
